version: "3.9"

services:
  server:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_DBNAME: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Password1
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Password1
    ports:
      - "5432:5432"

volumes:
  postgres_data:
