# Generated by Django 4.1.6 on 2023-02-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="previous_player",
            field=models.CharField(
                choices=[("X", "X"), ("O", "O")], default=None, max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="board",
            field=models.CharField(max_length=9),
        ),
    ]
