# Generated by Django 4.1.6 on 2023-02-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_previous_player_alter_game_board"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="previous_player",
            new_name="player",
        ),
    ]
